// Code generated by Slice Machine. DO NOT EDIT.

import Project from './Project';
import SceneObject from './SceneObject';

export {
	Project,
	SceneObject,
};

export const components = {
	project: Project,
	scene_object: SceneObject,
};
